# Generated by Django 3.0.7 on 2020-06-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_transaksi_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kategori',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
