# Generated by Django 3.0.7 on 2020-06-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20200620_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='harga',
            field=models.IntegerField(null=True),
        ),
    ]
