# Generated by Django 3.0.7 on 2020-07-07 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20200704_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='barang',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Kategori'),
        ),
        migrations.CreateModel(
            name='LogBarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('stok', models.IntegerField(blank=True, null=True)),
                ('barang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Barang')),
            ],
        ),
        migrations.CreateModel(
            name='BarangSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga_jual', models.IntegerField(null=True)),
                ('harga_beli', models.IntegerField(null=True)),
                ('barang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Barang')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Supplier')),
            ],
        ),
        migrations.AddField(
            model_name='barang',
            name='supplier',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.Supplier'),
        ),
    ]
