# Generated by Django 3.0.7 on 2020-07-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20200707_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='supplier',
            field=models.ManyToManyField(to='mainapp.Supplier'),
        ),
    ]
