# Generated by Django 3.0.7 on 2020-07-07 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20200707_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.BarangSupplier'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='barang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Barang'),
        ),
    ]
