# Generated by Django 3.0.7 on 2020-07-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20200707_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='BarangSupplier',
        ),
    ]
