# Generated by Django 3.0.7 on 2020-07-07 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20200707_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok', models.IntegerField(blank=True, null=True)),
                ('harga_jual', models.IntegerField(blank=True, null=True)),
                ('harga_beli', models.IntegerField(blank=True, null=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Barang')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Supplier')),
            ],
        ),
        migrations.AlterField(
            model_name='barang',
            name='supplier',
            field=models.ManyToManyField(through='mainapp.SupplierRelationship', to='mainapp.Supplier'),
        ),
    ]
