# Generated by Django 3.0.7 on 2020-07-07 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok', models.IntegerField(blank=True, default=0, null=True)),
                ('harga_jual', models.IntegerField(blank=True, default=0, null=True)),
                ('harga_beli', models.IntegerField(blank=True, default=0, null=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Barang')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idtrx', models.CharField(blank=True, max_length=12, null=True)),
                ('status', models.CharField(blank=True, choices=[('Keluar', 'Keluar'), ('Masuk', 'Masuk')], max_length=200, null=True)),
                ('harga_jual', models.IntegerField(blank=True, default=0, null=True)),
                ('harga_beli', models.IntegerField(blank=True, default=0, null=True)),
                ('harga', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('barang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Barang')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.SupplierRelationship')),
            ],
        ),
        migrations.CreateModel(
            name='RekapTransaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idtrx', models.CharField(blank=True, max_length=12, null=True)),
                ('status', models.CharField(choices=[('Keluar', 'Keluar'), ('Masuk', 'Masuk')], max_length=200, null=True)),
                ('harga_jual', models.IntegerField(blank=True, null=True)),
                ('harga_beli', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('barang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Barang')),
            ],
        ),
        migrations.CreateModel(
            name='LogBarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('stok', models.IntegerField(blank=True, null=True)),
                ('barang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Barang')),
            ],
        ),
        migrations.AddField(
            model_name='barang',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Kategori'),
        ),
        migrations.AddField(
            model_name='barang',
            name='supplier',
            field=models.ManyToManyField(through='mainapp.SupplierRelationship', to='mainapp.Supplier'),
        ),
    ]
