# Generated by Django 3.0.7 on 2020-06-20 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('stok', models.IntegerField()),
                ('harga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Keluar', 'keluar'), ('Masuk', 'masuk')], max_length=200, null=True)),
                ('barang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Barang')),
            ],
        ),
        migrations.AddField(
            model_name='barang',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Kategori'),
        ),
    ]
