# Generated by Django 3.0.7 on 2020-06-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='status',
            field=models.CharField(choices=[('Keluar', 'Keluar'), ('Masuk', 'Masuk')], max_length=200, null=True),
        ),
    ]
