# Generated by Django 3.0.7 on 2020-07-08 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200708_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbarang',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='logbarang',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierrelationship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
