# Generated by Django 3.0.7 on 2020-06-20 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200620_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Kategori'),
        ),
    ]
