# Generated by Django 3.0.7 on 2020-06-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200620_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
