# Generated by Django 3.0.7 on 2020-07-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200708_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kategori',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supplierrelationship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
