# Generated by Django 3.0.7 on 2020-06-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200620_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
