# Generated by Django 3.0.7 on 2020-07-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_logbarang_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekaptransaksi',
            name='kategori',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
