# Generated by Django 3.0.8 on 2020-07-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_rekaptransaksi_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
