# Generated by Django 3.0.8 on 2020-07-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_barang_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='user',
        ),
    ]
