# Generated by Django 3.0.8 on 2020-07-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_barang_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='kasir',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
