# Generated by Django 3.0.8 on 2020-07-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_transaksi_kasir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='kasir',
        ),
    ]
