# Generated by Django 3.0.7 on 2020-06-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20200622_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekaptransaksi',
            name='idtrx',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
