# Generated by Django 3.0.8 on 2020-07-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_transaksi_kasir'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbarang',
            name='kasir',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
