# Generated by Django 3.0.7 on 2020-07-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_rekaptransaksi_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekaptransaksi',
            name='status',
            field=models.CharField(choices=[('Keluar', 'Keluar'), ('Masuk', 'Masuk')], max_length=200, null=True),
        ),
    ]
